

inputs:
  brand_website: "https://www.myprotein.com"
  
  competitor_website: "https://www.optimumnutrition.com"
  
  service_locations:
    - "New York"
    - "Los Angeles" 
    - "Chicago"
    - "Houston"
    - "Phoenix"
    - "Philadelphia"
    - "San Antonio"
    - "San Diego"
    - "Dallas"
    - "Austin"
  
  budgets:
    shopping_ads: 8000   
    search_ads: 10000     
    pmax_ads: 2000       

conversion_rate: 0.025   
target_roas: 4.0         

gemini_api_key: "AIzaSyBR7vOGXb2whXg5YNkKda88glehgsJ5rd0"  

advanced:
  min_search_volume: 500       
  max_cpc_multiplier: 1.5       
  keyword_expansion_limit: 75  
  quality_score_target: 7     
  
  high_value_industries:
    - "insurance"
    - "legal" 
    - "finance"
    - "software"
    - "healthcare"
  
  negative_keywords:
    - "free"
    - "cheap" 
    - "wholesale"
    - "job"
    - "career"
    
  bid_adjustments:
    mobile: 0.9       
    tablet: 1.0     
    desktop: 1.1      
    
tracking:
  conversion_tracking: true
  enhanced_conversions: true
  google_analytics_linking: true
  attribution_model: "data_driven"
